manifest = "7645ffddd6c689cf324837d95f58a50e7c7e3aab9a242ed2982e0890ab3fd73a"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libjpeg"
target = "//:jpeg"

[lock."github.com/buckaroo-pm/luadist-libjpeg"]
versions = [ "branch=master" ]
revision = "ca608f3c842d921fa369e798b114c42444f5791d"
